In [1]:
import pandas as pd
import os
from scipy import stats
from scipy.stats import spearmanr
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import statsmodels.formula.api as smf

In [3]:
file_path = "/Users/remyfernando/Desktop/Noguchi Active/BSc Psychology/Year 3/Research Project/Project data/Qualtrics_ready_for_analysis.csv"
df = pd.read_csv(file_path)
df.head()

,participant_id,gender,age,more_than_one_device,device,maas_score,ios_pickups,non_ios_avg_pickups,inhibition_score
0,at483,Female,24,False,iPhone,3.27,46.0,NaN,45
1,we718,Female,22,False,iPhone,4.00,88.0,NaN,58
2,an142,Female,37,True,iPhone,3.73,44.0,NaN,57
3,es663,Female,33,False,Samsung,4.60,NaN,53.0,53
4,ba664,Female,33,False,Android,4.40,NaN,57.0,58

In [7]:
# Create a new column for z-scores and assign values based on device type
df['z_pickups'] = None
df.loc[df['ios_pickups'].notna(), 'z_pickups'] = stats.zscore(df['ios_pickups'].dropna())
df.loc[df['non_ios_avg_pickups'].notna(), 'z_pickups'] = stats.zscore(df['non_ios_avg_pickups'].dropna())
df["z_pickups"] = pd.to_numeric(df["z_pickups"], errors='coerce')

In [8]:
df.head()

,participant_id,gender,age,more_than_one_device,device,maas_score,ios_pickups,non_ios_avg_pickups,inhibition_score,z_pickups
0,at483,Female,24,False,iPhone,3.27,46.0,NaN,45,-1.239880
1,we718,Female,22,False,iPhone,4.00,88.0,NaN,58,-0.577710
2,an142,Female,37,True,iPhone,3.73,44.0,NaN,57,-1.271412
3,es663,Female,33,False,Samsung,4.60,NaN,53.0,53,-0.195952
4,ba664,Female,33,False,Android,4.40,NaN,57.0,58,-0.078034

## Run the regression analysis

### MUltiple regression

In [9]:
model1 = smf.ols('z_pickups ~ maas_score + inhibition_score', data=df).fit()
print(model1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              z_pickups   R-squared:                       0.124
Model:                            OLS   Adj. R-squared:                  0.061
Method:                 Least Squares   F-statistic:                     1.980
Date:                Tue, 24 Feb 2026   Prob (F-statistic):              0.157
Time:                        18:07:59   Log-Likelihood:                -41.937
No. Observations:                  31   AIC:                             89.87
Df Residuals:                      28   BIC:                             94.18
Df Model:                           2
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            1.0669      1.050      1.016      0.318      -1.084       3.218
maas_score           0.0421      0.287      0.147      0.884      -0.545       0.630
inhibition_score    -0.0255      0.014     -1.861      0.073      -0.054       0.003
==============================================================================
Omnibus:                        6.294   Durbin-Watson:                   1.892
Prob(Omnibus):                  0.043   Jarque-Bera (JB):                4.577
Skew:                           0.794   Prob(JB):                        0.101
Kurtosis:                       4.012   Cond. No.                         307.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.